[build]
  command = "hugo --minify --source build --destination build/docs && cp -R build/docs blog"
  publish = "/"

  [build.environment]
    HUGO_VERSION = "0.137.1"

[context.production]
  environment = { HUGO_VERSION = "0.137.1", HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true" }

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

# Redirigir subdominios y variantes HTTP a https://ewala.es
[[redirects]]
  from = "https://www.ewala.es/*"
  to = "https://ewala.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.ewala.es/*"
  to = "https://ewala.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://ewala.es/*"
  to = "https://ewala.es/:splat"
  status = 301
  force = true

# Redirigir solo la raíz con barra final a la raíz sin barra final
[[redirects]]
  from = "/"
  to = "/"
  status = 200