[build]
  command = "hugo --minify --source build --destination build/docs && cp -R build/docs blog"
  publish = "/"

  [build.environment]
    HUGO_VERSION = "0.137.1"

[context.production]
  environment = { HUGO_VERSION = "0.137.1", HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true" }

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/politica-privacidad"
  to = "/politica-privacidad/"
  status = 200

[[redirects]]
  from = "/politica-cookies"
  to = "/politica-cookies/"
  status = 200

[[redirects]]
  from = "/kit-digital-ciberseguridad-gestionada"
  to = "/kit-digital-ciberseguridad-gestionada/"
  status = 200

[[redirects]]
  from = "/aviso-legal"
  to = "/aviso-legal/"
  status = 200

[[redirects]]
  from = "/kit-consulting"
  to = "/kit-consulting/"
  status = 200

[[redirects]]
  from = "/kit-digital"
  to = "/kit-digital/"
  status = 200

[[redirects]]
  from = "/blog/tags/siem-y-xdr"
  to = "/blog/tags/siem-y-xdr/"
  status = 200

[[redirects]]
  from = "/blog/tags/soc"
  to = "/blog/tags/soc/"
  status = 200

[[redirects]]
  from = "/blog/tags/ataques-ransomware"
  to = "/blog/tags/ataques-ransomware/"
  status = 200

[[redirects]]
  from = "/blog/tags/ciberseguridad"
  to = "/blog/tags/ciberseguridad/"
  status = 200

[[redirects]]
  from = "/blog/tags/siem"
  to = "/blog/tags/siem/"
  status = 200

[[redirects]]
  from = "/blog/tags/cybersecurity-info"
  to = "/blog/tags/cybersecurity-info/"
  status = 200

[[redirects]]
  from = "/blog/tags/mdr"
  to = "/blog/tags/mdr/"
  status = 200

[[redirects]]
  from = "/blog/tags/soc-mdr"
  to = "/blog/tags/soc-mdr/"
  status = 200

[[redirects]]
  from = "/blog/tags/kit-digital"
  to = "/blog/tags/kit-digital/"
  status = 200

[[redirects]]
  from = "/blog/tags/ciberseguridad-avanzada"
  to = "/blog/tags/ciberseguridad-avanzada/"
  status = 200

[[redirects]]
  from = "/blog/tags/info"
  to = "/blog/tags/info/"
  status = 200

[[redirects]]
  from = "/blog/tags/av"
  to = "/blog/tags/av/"
  status = 200

[[redirects]]
  from = "/blog/tags/edr"
  to = "/blog/tags/edr/"
  status = 200

[[redirects]]
  from = "/blog/tags/protección-24/7"
  to = "/blog/tags/protección-24/7/"
  status = 200

[[redirects]]
  from = "/blog/tags/cybersecurity"
  to = "/blog/tags/cybersecurity/"
  status = 200