backend:
  name: github
  local_backend: true
  repo: EwalaIT/blogewala
  branch: master

media_folder: "static/images/" # Carpeta para cargar imágenes
public_folder: "/images" # Carpeta para mostrar imágenes en el sitio

collections:
  - name: "post"
    label: "Posts"
    folder: "content/posts" # Carpeta donde se guardan los posts en Hugo
    create: true
    slug: "{{slug}}" # Usar el slug directamente para una URL limpia
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - { label: "Categories", name: "categories", widget: "list", required: true, default: [] }
      - { label: "Tags", name: "tags", widget: "list", required: true, default: [] }
      - { label: "Developer", name: "developer", widget: "string", required: false, default: "Ewala" }
      - { label: "Tagline", name: "tagewala", widget: "string", required: false }
      - { label: "Header Image", name: "header_image", widget: "image", required: false }
      - { label: "Post Image", name: "postimage", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "string", required: false, default: "Ewala" }
      - { label: "Author Link", name: "authorlink", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
